version: "3"
services:
  database:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=112233
      - MYSQL_DATABASE=social
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  minios3:
    image: minio/minio
    container_name: minios3
    restart: always
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=tinhtute
      - MINIO_ROOT_PASSWORD=vodichtoanvutru
      - MINIO_ACCESS_KEY=2toxGr9rkiDV77KG
      - MINIO_SECRET_KEY=b1lnyNTlc0FJECAxCE4phPYrSKLcpx9G
    ports:
        - "9000:9000"
        - "9001:9001"
    volumes:
      - minios3:/data
volumes:
  mysql:
  minios3: