server:
  port: 8082
eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: newsfeed
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 112233
    url: jdbc:mysql://localhost:3306/social
    username: root
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework: debug
service:
  feign:
    token: "abc123-default"
    uri: "localhost:8081"
---
spring:
  config:
    activate:
      on-profile: "dev"
service:
  feign:
    token: 'abc123'
    uri: "localhost:8081"
---
spring:
  config:
    activate:
      on-profile: "prod"
service:
  feign:
    token: 'abc123-prod'
    uri: "localhost:8081"
---